name: http_client_helper
description: A Flutter plugin for http request with cancel and retry fuctions.
version: 2.0.4
homepage:  https://github.com/fluttercandies/http_client_helper

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^1.0.0

